/*
 * libctest.c - the in-OS half of the libc test (Phase 73). The other half,
 * userland/libc/tests/, runs the same library code against a FAKE kernel
 * on the host and can hammer it hundreds of thousands of times; this
 * program proves the same code works against the GENUINE kernel: real
 * int 0x80 syscalls, a real FAT32 and ext2 filesystem, a real ELF load,
 * real processes. kernel/task/exec_trust_demo.c runs it via
 * SYS_EXEC_TRUSTED (so it holds can_open_any_file and can_spawn - the
 * same trust TPROBE.ELF needs to write files) and checks its exit code;
 * tools/python/test_runner.py checks the "[libctest] PASS: ..." lines.
 *
 * Every failure prints "[libctest] FAIL: ..." - the uppercase word is
 * deliberate: it also trips test_runner.py's global no-FAIL assertion, so
 * a regression here can never slip through unnoticed.
 *
 * The same binary is also its own child process: "--envchild",
 * "--envempty" and "--envbig" make it check the environment the parent
 * passed and exit 0/non-zero, which is how environment inheritance is
 * tested across a real exec.
 */
#include <errno.h>
#include <novasys.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static int failed_groups;
static const char* first_fail_expr;
static int first_fail_line;

/* Records only the FIRST failed check of a group, so the report names
 * exactly what broke instead of a cascade. */
#define CHECK(c) do { if (!(c) && first_fail_expr == NULL) { \
    first_fail_expr = #c; first_fail_line = __LINE__; } } while (0)

static void group_begin(void) {
    first_fail_expr = NULL;
    first_fail_line = 0;
}

static void group_end(const char* name) {
    if (first_fail_expr == NULL) {
        printf("[libctest] PASS: %s\n", name);
    } else {
        failed_groups++;
        printf("[libctest] FAIL: %s (line %d: %s; errno=%d %s)\n", name,
               first_fail_line, first_fail_expr, errno, strerror(errno));
    }
}

/* Deterministic content, shared with tools/fixtures/ext2root/EXT2BIG.BIN
 * (generated by the same formula). */
static unsigned char pat(unsigned int i) {
    return (unsigned char)(i * 7u + (i >> 8) + 3u);
}

static int pattern_ok(const unsigned char* p, unsigned int n,
                      unsigned int base) {
    for (unsigned int i = 0; i < n; i++) {
        if (p[i] != pat(base + i)) {
            return 0;
        }
    }
    return 1;
}

/* Reads a file end to end through the raw syscalls in pieces of `piece`
 * bytes - odd sizes make the kernel start reads part-way into a FAT32
 * cluster / ext2 block, which whole-file fopen() (4 KiB-aligned reads)
 * never does. Returns the number of bytes read, or -1 on any mismatch. */
static int raw_read_all(const char* name, unsigned int piece,
                        unsigned int expect_len) {
    int h = sys_open(name);
    if (h < 0) {
        return -1;
    }
    unsigned char buf[512];
    unsigned int total = 0;
    for (;;) {
        int n = sys_read(h, buf, (int)piece);
        if (n < 0) {
            sys_close(h);
            return -1;
        }
        if (n == 0) {
            break;
        }
        if (!pattern_ok(buf, (unsigned int)n, total)) {
            sys_close(h);
            return -1;
        }
        total += (unsigned int)n;
    }
    sys_close(h);
    return total == expect_len ? (int)total : -1;
}

/* ------------------------------------------------------------------ */

static void test_allocator(void) {
    group_begin();

    unsigned char* p = (unsigned char*)malloc(100);
    CHECK(p != NULL && ((unsigned int)p & 15) == 0);
    for (int i = 0; i < 100; i++) p[i] = pat((unsigned int)i);

    unsigned char* q = (unsigned char*)realloc(p, 5000);       /* grow */
    CHECK(q != NULL && pattern_ok(q, 100, 0));
    for (int i = 0; i < 5000; i++) q[i] = pat((unsigned int)i);
    q = (unsigned char*)realloc(q, 40);                         /* shrink */
    CHECK(q != NULL && pattern_ok(q, 40, 0));

    /* Interleaved growth of two buffers forces real moves. */
    unsigned char* a = (unsigned char*)malloc(64);
    unsigned char* b = (unsigned char*)malloc(64);
    CHECK(a != NULL && b != NULL);
    for (int i = 0; i < 64; i++) { a[i] = pat((unsigned int)i); b[i] = pat((unsigned int)i + 7); }
    for (unsigned int sz = 128; sz <= 8192; sz *= 2) {
        a = (unsigned char*)realloc(a, sz);
        b = (unsigned char*)realloc(b, sz);
        CHECK(a != NULL && b != NULL);
        if (a == NULL || b == NULL) break;
        CHECK(pattern_ok(a, 64, 0) && pattern_ok(b, 64, 7));
    }

    /* Freed memory is reused and coalesced: after freeing everything, a
     * fresh large request must not need to grow the heap. */
    free(a);
    free(b);
    free(q);
    void* brk_before = sys_sbrk(0);
    void* big = malloc(9000);
    CHECK(big != NULL);
    CHECK(sys_sbrk(0) == brk_before);
    free(big);

    /* calloc zeroes even memory that was just used and freed. */
    unsigned char* dirty = (unsigned char*)malloc(256);
    for (int i = 0; i < 256; i++) dirty[i] = 0xAA;
    free(dirty);
    unsigned char* z = (unsigned char*)calloc(16, 16);
    int all_zero = z != NULL;
    for (int i = 0; z != NULL && i < 256; i++) if (z[i] != 0) all_zero = 0;
    CHECK(all_zero);
    free(z);

    /* Guard rails: an impossible size fails cleanly and leaves the
     * original block valid (asking the kernel for that much would
     * instead eat all physical memory). */
    unsigned char* keep = (unsigned char*)malloc(32);
    for (int i = 0; i < 32; i++) keep[i] = pat((unsigned int)i);
    errno = 0;
    CHECK(realloc(keep, 0x50000000u) == NULL && errno == ENOMEM);
    CHECK(pattern_ok(keep, 32, 0));
    errno = 0;
    CHECK(calloc(65536, 65537) == NULL && errno == ENOMEM);
    free(keep);

    group_end("malloc/realloc/calloc allocator");
}

static void test_errno(void) {
    group_begin();
    errno = 0;
    FILE* f = fopen("NOSUCH.TXT", "r");
    CHECK(f == NULL && errno == ENOENT);
    CHECK(strcmp(strerror(errno), "No such file or directory") == 0);
    errno = 0;
    CHECK(fopen("WAYTOOLONGNAME.TXT", "r") == NULL && errno == ENAMETOOLONG);
    errno = 0;
    CHECK(fopen("HELLO.TXT", "q") == NULL && errno == EINVAL);
    errno = 0;
    CHECK(remove("NOSUCH.TXT") == -1 && errno == ENOENT);
    group_end("errno set by failing library calls");
}

static void test_file_roundtrip(void) {
    group_begin();
    remove("LCTEST.TXT");

    FILE* f = fopen("LCTEST.TXT", "w");
    CHECK(f != NULL);
    if (f == NULL) {
        group_end("fopen/fread/fwrite/fclose file round trip");
        return;
    }
    CHECK(fprintf(f, "line %d\n", 1) == 7);
    CHECK(fputs("second line\n", f) >= 0);
    CHECK(fclose(f) == 0);

    f = fopen("LCTEST.TXT", "r");
    CHECK(f != NULL);
    char line[64];
    if (f != NULL) {
        CHECK(fgets(line, sizeof line, f) == line && strcmp(line, "line 1\n") == 0);
        CHECK(fgets(line, sizeof line, f) == line && strcmp(line, "second line\n") == 0);
        CHECK(fgets(line, sizeof line, f) == NULL && feof(f));
        fclose(f);
    }

    /* append, then read the whole thing back in one fread */
    f = fopen("LCTEST.TXT", "a");
    CHECK(f != NULL);
    if (f != NULL) {
        CHECK(fputs("third\n", f) >= 0);
        CHECK(fclose(f) == 0);
    }
    f = fopen("LCTEST.TXT", "r");
    CHECK(f != NULL);
    if (f != NULL) {
        CHECK(fseek(f, 0, SEEK_END) == 0 && ftell(f) == 25);
        rewind(f);
        char all[64];
        CHECK(fread(all, 1, sizeof all, f) == 25);
        CHECK(memcmp(all, "line 1\nsecond line\nthird\n", 25) == 0);
        fclose(f);
    }

    /* r+ overwrites in place and keeps the rest */
    f = fopen("LCTEST.TXT", "r+");
    CHECK(f != NULL);
    if (f != NULL) {
        CHECK(fseek(f, 5, SEEK_SET) == 0 && fputc('X', f) == 'X');
        CHECK(fclose(f) == 0);
    }
    f = fopen("LCTEST.TXT", "r");
    if (f != NULL) {
        CHECK(fgets(line, sizeof line, f) == line && strcmp(line, "line X\n") == 0);
        fclose(f);
    }

    /* "w" on an existing file empties it */
    f = fopen("LCTEST.TXT", "w");
    CHECK(f != NULL);
    if (f != NULL) {
        CHECK(fclose(f) == 0);
    }
    f = fopen("LCTEST.TXT", "r");
    CHECK(f != NULL && fgetc(f) == EOF && feof(f));
    if (f != NULL) fclose(f);

    CHECK(remove("LCTEST.TXT") == 0);
    errno = 0;
    CHECK(fopen("LCTEST.TXT", "r") == NULL && errno == ENOENT);
    group_end("fopen/fread/fwrite/fclose file round trip");
}

/* 10000 bytes: three kernel reads (4096 + 4096 + 1808) - the case the
 * old SYS_READ silently truncated at 4096. */
static void test_large_fat32_file(void) {
    group_begin();
    remove("LCBIG.BIN");
    enum { N = 10000 };

    FILE* f = fopen("LCBIG.BIN", "wb");
    CHECK(f != NULL);
    if (f == NULL) {
        group_end("file larger than one kernel read (10000 bytes) via FAT32");
        return;
    }
    unsigned char piece[250];
    unsigned int off = 0;
    while (off < N) {
        for (unsigned int k = 0; k < sizeof piece; k++) piece[k] = pat(off + k);
        CHECK(fwrite(piece, 1, sizeof piece, f) == sizeof piece);
        off += (unsigned int)sizeof piece;
    }
    CHECK(fclose(f) == 0);

    static unsigned char back[N + 16];
    f = fopen("LCBIG.BIN", "rb");
    CHECK(f != NULL);
    if (f != NULL) {
        CHECK(fread(back, 1, sizeof back, f) == N);
        CHECK(feof(f));
        CHECK(pattern_ok(back, N, 0));
        /* a read that straddles the 4096 and 8192 kernel-read boundaries */
        CHECK(fseek(f, 4090, SEEK_SET) == 0);
        unsigned char x[20];
        CHECK(fread(x, 1, 20, f) == 20 && pattern_ok(x, 20, 4090));
        CHECK(fseek(f, 8185, SEEK_SET) == 0);
        CHECK(fread(x, 1, 20, f) == 20 && pattern_ok(x, 20, 8185));
        fclose(f);
    }

    /* raw syscalls in odd-sized pieces: reads that begin mid-cluster.
     * Two sizes are enough to make the offsets unaligned in different
     * ways; more (or smaller) only costs time - every SYS_READ is a real
     * directory walk and cluster read on QEMU's emulated disk, and a
     * 7-byte piece size (~1,400 calls) once made this test miss the
     * boot test's time window on a slower machine. */
    CHECK(raw_read_all("LCBIG.BIN", 333, N) == N);
    CHECK(raw_read_all("LCBIG.BIN", 509, N) == N);

    /* max_len 0 is an existence probe: 0 if present, -1 if missing */
    int h = sys_open("LCBIG.BIN");
    char c;
    CHECK(h >= 0 && sys_read(h, &c, 0) == 0);
    if (h >= 0) sys_close(h);
    h = sys_open("NOSUCH.BIN");
    CHECK(h >= 0 && sys_read(h, &c, 0) == -1);
    if (h >= 0) sys_close(h);

    CHECK(remove("LCBIG.BIN") == 0);
    group_end("file larger than one kernel read (10000 bytes) via FAT32");
}

static void test_ext2(void) {
    group_begin();

    FILE* f = fopen("EXT2TEST.TXT", "r");
    CHECK(f != NULL);
    if (f != NULL) {
        char buf[80];
        size_t n = fread(buf, 1, sizeof buf - 1, f);
        buf[n] = '\0';
        CHECK(strncmp(buf, "Hello from a real ext2 filesystem read by NovaOS!", 49) == 0);
        fclose(f);
    }

    /* 20000 bytes: past ext2's 12 direct blocks when the block size is
     * 1 KiB, so this reads through the singly-indirect block too. */
    static unsigned char big[20000 + 16];
    f = fopen("EXT2BIG.BIN", "rb");
    CHECK(f != NULL);
    if (f != NULL) {
        CHECK(fread(big, 1, sizeof big, f) == 20000);
        CHECK(pattern_ok(big, 20000, 0));
        fclose(f);
    }
    CHECK(raw_read_all("EXT2BIG.BIN", 333, 20000) == 20000);
    CHECK(raw_read_all("EXT2BIG.BIN", 509, 20000) == 20000);
    group_end("ext2 file (20000 bytes, direct+indirect blocks) via fopen");
}

static void test_environment(void) {
    group_begin();
    CHECK(getenv("NOVA_T1") == NULL);
    CHECK(setenv("NOVA_T1", "alpha", 1) == 0);
    CHECK(strcmp(getenv("NOVA_T1"), "alpha") == 0);
    CHECK(setenv("NOVA_T1", "beta", 0) == 0);               /* no overwrite */
    CHECK(strcmp(getenv("NOVA_T1"), "alpha") == 0);
    CHECK(setenv("NOVA_T1", "gamma", 1) == 0);
    CHECK(strcmp(getenv("NOVA_T1"), "gamma") == 0);
    static char mine[] = "NOVA_T2=put";
    CHECK(putenv(mine) == 0 && strcmp(getenv("NOVA_T2"), "put") == 0);
    CHECK(unsetenv("NOVA_T1") == 0 && getenv("NOVA_T1") == NULL);
    CHECK(unsetenv("NOVA_T2") == 0 && getenv("NOVA_T2") == NULL);
    errno = 0;
    CHECK(setenv("BAD=NAME", "x", 1) == -1 && errno == EINVAL);
    group_end("environment variables get/set/unset/putenv");
}

/* ------------------------------------------------------------------ */

static int spawn_wait(const char* mode, int trusted_env_explicit,
                      char** explicit_env) {
    char* av[3] = { (char*)"LIBCTEST.ELF", (char*)mode, NULL };
    int pid = trusted_env_explicit
                  ? sys_exec_trusted_env("LIBCTEST.ELF", av, 2, explicit_env)
                  : sys_exec_trusted("LIBCTEST.ELF", av, 2);
    if (pid < 0) {
        return -1000;
    }
    return sys_wait(pid);
}

static void test_env_inheritance(void) {
    group_begin();
    clearenv();
    CHECK(setenv("NOVA_ENV_TEST", "from-parent", 1) == 0);
    CHECK(setenv("NOVA_ENV_TEST2", "two words", 1) == 0);

    /* default: the libc sys_exec_trusted() wrapper hands over environ */
    CHECK(spawn_wait("--envchild", 0, NULL) == 0);

    /* an explicit NULL environment overrides it: the child sees none */
    CHECK(spawn_wait("--envempty", 1, NULL) == 0);

    /* an environment exactly at the 4096-byte limit is accepted and
     * arrives intact: "N=" + 4093 characters + NUL == 4096 */
    static char bigenv[4096];
    bigenv[0] = 'N'; bigenv[1] = '=';
    for (int i = 2; i < 4095; i++) bigenv[i] = 'x';
    bigenv[4095] = '\0';
    char* big_env[2] = { bigenv, NULL };
    CHECK(spawn_wait("--envbig", 1, big_env) == 0);
    group_end("environment inherited by a child process");
}

static void test_env_limits(void) {
    group_begin();
    char* av[2] = { (char*)"LIBCTEST.ELF", NULL };

    /* 33 variables: one over the limit. The kernel must refuse (-1)
     * rather than truncate silently - bypassing libc's own setenv()
     * limit by building the array by hand. */
    char* many[34];
    for (int i = 0; i < 33; i++) many[i] = (char*)"A=1";
    many[33] = NULL;
    CHECK(sys_exec_trusted_env("LIBCTEST.ELF", av, 1, many) == -1);

    /* one byte over 4096 */
    static char over[4098];
    over[0] = 'H'; over[1] = '=';
    for (int i = 2; i < 4096; i++) over[i] = 'h';
    over[4096] = '\0';                       /* strlen 4096 + NUL = 4097 */
    char* over_env[2] = { over, NULL };
    CHECK(sys_exec_trusted_env("LIBCTEST.ELF", av, 1, over_env) == -1);

    /* libc itself refuses to build such an environment, so it can
     * never hand its own children one the kernel would reject */
    clearenv();
    errno = 0;
    CHECK(setenv("BIG", over, 1) == -1 && errno == ENOMEM);
    group_end("kernel enforces the environment size limits");
}

static void test_printf(void) {
    group_begin();
    char buf[64];
    int n = snprintf(buf, sizeof buf, "%5d|%-5s|%04x|%c|%%|%s|%u", 42, "ab",
                     0xbeef, 'z', "end", 4000000000u);
    CHECK(n == 35 && strcmp(buf, "   42|ab   |beef|z|%|end|4000000000") == 0);
    CHECK(snprintf(buf, 4, "%s", "abcdef") == 6 && strcmp(buf, "abc") == 0);
    CHECK(snprintf(NULL, 0, "%s", "hello") == 5);
    CHECK(snprintf(buf, sizeof buf, "%d", -2147483647 - 1) == 11 &&
          strcmp(buf, "-2147483648") == 0);

    /* printf returns the length and, unlike the old fixed-512-byte
     * version, never truncates */
    int len = printf("[libctest] printf length probe %d\n", 12345);
    CHECK(len == 37);
    static char longs[700];
    for (int i = 0; i < 699; i++) longs[i] = (char)('a' + i % 26);
    longs[699] = '\0';
    CHECK(fprintf(stdout, "%s\n", longs) == 700);
    group_end("printf/snprintf formatting");
}

/* ------------------------------------------------------------------ */

static int child_main(const char* mode) {
    if (strcmp(mode, "--envchild") == 0) {
        const char* a = getenv("NOVA_ENV_TEST");
        const char* b = getenv("NOVA_ENV_TEST2");
        int n = 0;
        while (environ != NULL && environ[n] != NULL) n++;
        int ok = a != NULL && strcmp(a, "from-parent") == 0 &&
                 b != NULL && strcmp(b, "two words") == 0 && n == 2;
        /* and the child can extend what it inherited */
        ok = ok && setenv("NOVA_CHILD", "yes", 1) == 0 && getenv("NOVA_CHILD") != NULL;
        printf("[libctest-child] envchild %s (vars=%d)\n", ok ? "ok" : "MISMATCH", n);
        return ok ? 0 : 10;
    }
    if (strcmp(mode, "--envempty") == 0) {
        int ok = getenv("NOVA_ENV_TEST") == NULL &&
                 (environ == NULL || environ[0] == NULL);
        printf("[libctest-child] envempty %s\n", ok ? "ok" : "MISMATCH");
        return ok ? 0 : 11;
    }
    if (strcmp(mode, "--envbig") == 0) {
        const char* v = getenv("N");
        int ok = v != NULL && strlen(v) == 4093;
        for (int i = 0; ok && i < 4093; i++) if (v[i] != 'x') ok = 0;
        printf("[libctest-child] envbig %s\n", ok ? "ok" : "MISMATCH");
        return ok ? 0 : 12;
    }
    return 13;
}

int main(int argc, char** argv, char** envp) {
    (void)envp;
    if (argc >= 2) {
        return child_main(argv[1]);
    }

    test_allocator();
    test_errno();
    test_file_roundtrip();
    test_large_fat32_file();
    test_ext2();
    test_environment();
    test_env_inheritance();
    test_env_limits();
    test_printf();

    printf("[libctest] DONE: 9 groups, %d failed\n", failed_groups);
    return failed_groups;
}
